# __Part 1: PyTorch Basics__

PyTorch is an open source machine learning library based on the [Torch](http://torch.ch/) library. It is primarily developed by [Facebook's AI Research lab (FAIR)](https://ai.facebook.com/).

# Pre-requisites

This tutorial assumes you already have some basic knowledge of programming with [Python](https://www.python.org/). If not there are loads of Python tutorials available online. I just did a quick Google search and found [this](https://www.tutorialspoint.com/python/index.htm) and [this](https://www.learnpython.org/).  

# Setup

It is recommended to run this notebook in [Google Colab](https://colab.research.google.com/notebooks/intro.ipynb#recent=true). You can also run this notebook on your machine by [installing PyTorch](https://pytorch.org/get-started/locally/) locally.

In [1]:
from __future__ import print_function
import torch
import sys
import numpy as np
print(sys.version)
print(torch.__version__)

3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]
1.4.0


# Tensors

Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(x)

tensor([[2.7980e-09, 6.3619e-43, 2.7980e-09],
        [6.3619e-43, 2.7981e-09, 6.3619e-43],
        [2.7981e-09, 6.3619e-43, 2.7978e-09],
        [6.3619e-43, 2.7978e-09, 6.3619e-43],
        [2.7983e-09, 6.3619e-43, 2.7983e-09]])


In [3]:
# Construct a 5x3 matrix, randomly initialized
x = torch.rand(5, 3)
print(x)

tensor([[0.5170, 0.6947, 0.6664],
        [0.2518, 0.7912, 0.3462],
        [0.2508, 0.4258, 0.7869],
        [0.3101, 0.5825, 0.6662],
        [0.7112, 0.2578, 0.9234]])


In [4]:
# Construct a 5x3 matrix, initialized with zero
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# Construct a 2x2 matrix, initialized with custom values
x = torch.tensor([[5.5, 3], [0.1, 1]])
print(x)

tensor([[5.5000, 3.0000],
        [0.1000, 1.0000]])


# Operators

You can find the list of all operations described [here](https://pytorch.org/docs/stable/torch.html).

In [6]:
x = torch.ones(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

# Addition
print(x + y) # alternatively, print(torch.add(x, y)) 

# Subtraction
print(x - y) # alternatively, print(torch.sub(x, y))

# Element-wise multiplication
print(x * y) # alternatively, print(torch.mul(x, y)) 

# Matrix multiplication
print(torch.mm(x, y))

tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3047, 0.8861],
        [0.3961, 0.5160]])
tensor([[1.3047, 1.8861],
        [1.3961, 1.5160]])
tensor([[0.6953, 0.1139],
        [0.6039, 0.4840]])
tensor([[0.3047, 0.8861],
        [0.3961, 0.5160]])
tensor([[0.7008, 1.4021],
        [0.7008, 1.4021]])


# Tensors ⇄ Numpy

In [7]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [8]:
# Torch tensor to NumPy array
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [9]:
# NumPy array to torch tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


# CUDA Tensors

[CUDA](https://en.wikipedia.org/wiki/CUDA) is a parallel computing platform and application programming interface (API) model created by [Nvidia](https://www.nvidia.com/en-us/location-selector/). It is used to allow computing on the GPU.

In [10]:
print('Is GPU available?:', torch.cuda.is_available())
print('How many GPUs?:', torch.cuda.device_count())
print('Which id GPU is currently being used?:', torch.cuda.current_device())
print('What model GPU is currently being used?:', torch.cuda.get_device_name(0))

Is GPU available?: True
How many GPUs?: 1
Which id GPU is currently being used?: 0
What model GPU is currently being used?: GeForce GTX 1050


In [11]:
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda:0")        # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z.is_cuda)                       # check if variable is on the GPU 
    print(z)

True
tensor([[2., 2.],
        [2., 2.]], device='cuda:0')


In [12]:
# Move tensor out of GPU to CPU
print(z.to("cpu"))

tensor([[2., 2.],
        [2., 2.]])


# Autograd: Automatic differentiation

The autograd package provides automatic differentiation for all operations on Tensors. The system is based on tape-based automatic differentiation. A recorder records what operations have been performed, and then it replays it backward to compute the gradients. It is a define-by-run framework, which means that your backpropagation is defined by how your code is run, and that every single iteration can be different. More details if you are interested [here](https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html).

In [13]:
# Create tensors and set requires_grad=True to track computation with it
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

# Build a computational graph
y = w * x + b 

# Compute the gradients
y.backward()

# Calculate the gradients
print(x.grad)    # x.grad = 2 
print(w.grad)    # w.grad = 1 
print(b.grad)    # b.grad = 1 

tensor(2.)
tensor(1.)
tensor(1.)


In [14]:
# Create a non-scalar tensor
x = torch.tensor([2., 3., 4.], requires_grad=True)

# Build a computational graph
y = x * x * 2

# Specify gradient argument
v = torch.tensor([1., 1., 0.1])

# Compute gradients
y.backward(v)

# Calculate the gradients
print(x.grad)

tensor([ 8.0000, 12.0000,  1.6000])


In [15]:
# Check if we are tracking computation
x = torch.tensor(3., requires_grad=True)
print('Requires grad?:', x.requires_grad)
print('Requires grad?:', (x**2).requires_grad)

# Stop autograd from tracking history on Tensors 
with torch.no_grad():
  print('Requires grad?:', (x**2).requires_grad)

# Use detach to remove from computation history
print('Requires grad?:', x.detach().requires_grad)

Requires grad?: True
Requires grad?: True
Requires grad?: False
Requires grad?: False
